baseURL = 'https://hoohyunn.github.io/portfolio_2025/'
languageCode = 'en-us'
title = 'Aymeric Combes'

theme = 'ananke'

[menu] 

[[menu.main]]
identifier = "about"
name = "À propos de moi"
url = "/a-propos-de-moi/"
weight = 4
